### ISSUE TITLE
Problems with rounded corners when generating bitmaps

### ISSUE THREAD

**Issue by Jeluchu** [PatilShreyas/Capturable#8]
Inside the example in the repository, I have tried to see the things that can be done and I have seen that once inside the card (in this case the example), everything you put with a RoundedCornerShape, does not reproduce it, but it is shown as a rectangle with square corners

> To reproduce the problem, follow these steps
In the example Code
1. Go to BookingConfirmedContent Composable function
2. Add inside the Modifier of the Text containing "Booking Confirmed" the following: `.clip(RoundedCornerShape(16.dp)).background(Color.Red)`
3. Compile and see that the text "Booking Confirmed" has a red background with rounded corners
4. Click on the "Preview Ticket Image" button and you will see that the red background with rounded corners has changed to a red background with square corners.

**Comment by PatilShreyas** [comment]
Hi @Jeluchu, thanks for reporting this issue. I verified it and looks like a genuine issue.

**Comment by PatilShreyas** [comment]
@Jeluchu Looks like it's already discussed here https://issuetracker.google.com/issues/208339581

Actually, there's no need to clip and then add a background modifier. This thing can be done at one time altogether with `background()` modifier only. This modifier has second optional parameter as `shape` where you can specify shape of a background.

Example:

```kt
Box(Modifier.background(Color.Magenta, shape = RoundedCornerShape(32.dp))) {
    Text(
        "Booking Confirmed",
        style = MaterialTheme.typography.h4
    )
}
```

This works ✅. Check the demonstration here 👇

https://user-images.githubusercontent.com/19620536/150345286-da00b490-5183-4531-91c5-10b9d51d4cb9.mp4

Closing this issue since it's not related to the library.

**Comment by Jeluchu** [comment]
But the problem is not that @PatilShreyas, since I am using that function that I was showing you in another area and it works without problems, when capturing the bitmap, it always comes as null, so I can't save the bitmap in any case

There you can see the real problem, the bitmap is null and error shows a different message

[Image of the debugging problem](https://ibb.co/yF99y1m)
